#!/bin/bash
echo "🐳 Docker Setup - Color Optimizer"
echo "================================="
echo ""
echo "Uso: docker-compose up --build"
echo ""
echo "Servizi:"
echo "  Frontend: http://localhost:8080"
echo "  Backend:  http://localhost:8000/docs"
echo ""
echo "Test: python test_docker_setup.py"
